// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4UNuuaJnWeK8x3dnS5lUT6QRSiKhFwqI',
    appId: '1:309596549418:web:d260ddc33c618e2825ae53',
    messagingSenderId: '309596549418',
    projectId: 'football-trivia-24',
    authDomain: 'football-trivia-24.firebaseapp.com',
    storageBucket: 'football-trivia-24.firebasestorage.app',
    measurementId: 'G-PKNE1W6XML',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHY9MF-SA0aXwCIfJBy23lJTu13qro9uA',
    appId: '1:309596549418:android:b0b43f54835237e025ae53',
    messagingSenderId: '309596549418',
    projectId: 'football-trivia-24',
    storageBucket: 'football-trivia-24.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOYlAWHoWQhdZ2ikUyp4NPF3UCjwE0N2w',
    appId: '1:309596549418:ios:a5f72b1f7786ee1b25ae53',
    messagingSenderId: '309596549418',
    projectId: 'football-trivia-24',
    storageBucket: 'football-trivia-24.firebasestorage.app',
    iosBundleId: 'com.example.footballTrivia',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCOYlAWHoWQhdZ2ikUyp4NPF3UCjwE0N2w',
    appId: '1:309596549418:ios:a5f72b1f7786ee1b25ae53',
    messagingSenderId: '309596549418',
    projectId: 'football-trivia-24',
    storageBucket: 'football-trivia-24.firebasestorage.app',
    iosBundleId: 'com.example.footballTrivia',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC4UNuuaJnWeK8x3dnS5lUT6QRSiKhFwqI',
    appId: '1:309596549418:web:d6d5ee870c5ca02e25ae53',
    messagingSenderId: '309596549418',
    projectId: 'football-trivia-24',
    authDomain: 'football-trivia-24.firebaseapp.com',
    storageBucket: 'football-trivia-24.firebasestorage.app',
    measurementId: 'G-J76LQ48P6B',
  );
}
